name: Release and Publish

on:
  push:
    tags:
       - '*'

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: lvjiaxuan/github-action-templates/.github/workflows/lvr-release.yml@main
    secrets: inherit

  publish:
    uses: lvjiaxuan/github-action-templates/.github/workflows/pnpm-ni.yml@main
    with:
      install: true
      run_script: pnpm -r publish --access public --no-git-checks
    secrets: inherit

  cnpm_sync:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g cnpm

      - run: cnpm sync @lvjiaxuan/eslint-config @lvjiaxuan/eslint-config-js @lvjiaxuan/eslint-config-ts @lvjiaxuan/eslint-config-vue @lvjiaxuan/eslint-plugin --sync-publish